### ISSUE TITLE
Python 3.7 安装编码问题

### ISSUE THREAD

**Issue by ykyyky12345** [WALL-E/dubbo-telnet-py#3]
Python 3.7 安装时出现
File "C:\Users\huangpo\AppData\Local\Temp\pycharm-packaging\dubbo-telnet\setup.py", line 24, in <module>
        long_description=open("README.PYPI").read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 163: illegal multibyte sequence

##############################################################################
修改 setup.py 为
long_description=open("README.PYPI", encoding='utf-8').read()
后可以正常安装. 随后使用 Python 2.7 未出现此问题, 建议加入版本判断或统一使用 utf-8 编码.

**Comment by WALL-E** [comment]
非常感谢  @ykyyky12345
